version: "3.7"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: dev
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hrmkg2024
      MYSQL_DATABASE: hrmkg
      MYSQL_USER: hrmkg
      MYSQL_PASSWORD: hrmkg2024
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
